export enum Actions {
  CHANGE_ID = "CHANGE_ID",
  CHANGE_SHOW_MODAL = "CHANGE_SHOW_MODAL",
  CHANGE_STATE_MODAL_LOGOUT = "CHANGE_STATE_MODAL_LOGOUT",
  CHANGE_LOGOUT_STATE = "CHANGE_LOGOUT_STATE",
  CHANGE_TEXT = "CHANGE_TEXT",
  CHANGE_USER = "CHANGE_USER",
  LOGOUT_USER = "LOGOUT_USER",
  CHANGE_USER_ROLE = "CHANGE_USER_ROLE",
  CHECK_USER = "CHECK_USER",
}
