export enum ActionsForUser {
  CHANGE_USER = "CHANGE_USER",
  LOGOUT_USER = "LOGOUT_USER",
  CHANGE_USER_ROLE = "CHANGE_USER_ROLE",
  CHANGE_USER_NAME = "CHANGE_USER_NAME",
  CHECK_USER = "CHECK_USER",
  GET_USERS = "GET_USERS",
}
