export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const FILMS_ROUTE = '/films'
export const BASKET_ROUTE = '/basket'
export const ABOUTFILM_ROUTE = '/about_film'
export const ABOUTUS_ROUTE = '/about_us'